version: '3'

services:

  server:
    build: ./server
    container_name: server
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/srv/app/server/src
    command: npm run dev

  client:
    build: ./client
    container_name: client
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/college_client/src:/srv/app/client/src
      - ./client/college_client/public:/srv/app/client/public
    links:
      - server
    command: npm run start

